// export interface IRecipe{
//     aggregateLikes: number
//     analyzedInstructions: []
//     cheap: boolean
//     cookingMinutes: number
//     creditsText: string
//     cuisines: []
//     dairyFree: boolean
//     diets: []
//     dishTypes: []
//     extendedIngredients: []
//     gaps: string
//     glutenFree: boolean
//     healthScore: number
//     id: number
//     image: string
//     imageType: string
//     instructions: string
//     license: string
//     lowFodmap: boolean
//     occasions: []
//     originalId: null
//     preparationMinutes: number
//     pricePerServing: number
//     servings: number
//     sourceName: string
//     sourceUrl: string
//     spoonacularSourceUrl: string
//     summary: string
//     sustainable: boolean
//     title: string
//     vegan: boolean
//     vegetarian: boolean
//     veryHealthy: boolean
//     veryPopular: boolean
//     weightWatcherSmartPoints: number
// }